### ISSUE TITLE
Simplification of the guide and setup process.

### ISSUE THREAD

**Issue by WilliamDue** [diku-dk/futhark-ci#2]
The guide needs to be simplified:
- It needs to be more precise.
- It should rely more on the code.
- Mention where runners can be see is active.
- The guide should document properties of the self-hosted runner.
  Some possible properties are:
  - Does the runner do one job at a time?
  - Does the runner clean up after each job is executed?/Does the work folder need to be empty.
  - Can runners share a folder?
  - Can tokens be reused?

The setup process needs to be simplified:
- The self-hosted runner needs to be setup and started with a script.
- The script will be implemented in Python 3
- The script should only take three arguments a token, labels and name.
- The labels should be renamed in lowercase to cuda, opencl and multicore.

**Comment by athas** [comment]
Important notes:

Working directory is *not* cleared from one run to the next.

The runner remembers the environment variables that were set when it was *configured*, not when it *runs*, in an .env file.

**Comment by WilliamDue** [comment]
The branch [simplification](https://github.com/diku-dk/futhark-ci/tree/simplification) has what I believe could be a solution to this issue inside runner.py and self-hosted-runner.md.

**Comment by athas** [comment]
Do a PR and I will review the guide.
